# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_subject', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'mark_details',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_dob', models.DateField(null=True)),
                ('student_phone_number', models.IntegerField(blank=True, null=True)),
                ('student_address', models.TextField()),
                ('student_marks', models.IntegerField(blank=True, null=True)),
                ('student_rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'student_details',
            },
        ),
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=80, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=15, unique=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'subject_details',
            },
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_address', models.TextField()),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_name', to=settings.AUTH_USER_MODEL)),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_code', to='school_profile.SubjectDetails')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'teacher_details',
            },
        ),
        migrations.AddIndex(
            model_name='subjectdetails',
            index=models.Index(fields=['subject_code'], name='subject_details_idx1'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='student_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_code', to='school_profile.SubjectDetails'),
        ),
        migrations.AddField(
            model_name='markdetails',
            name='mark_subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_subject_code', to='school_profile.SubjectDetails'),
        ),
        migrations.AddIndex(
            model_name='teacherdetails',
            index=models.Index(fields=['teacher_name'], name='teacher_details_idx1'),
        ),
        migrations.AddIndex(
            model_name='studentdetails',
            index=models.Index(fields=['student_name'], name='student_details_idx1'),
        ),
        migrations.AddIndex(
            model_name='markdetails',
            index=models.Index(fields=['mark_subject'], name='mark_details_idx1'),
        ),
    ]
