# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='student_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
