# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0002_auto_20190603_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdetails',
            name='mark_subject_code',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='student_subject',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='student_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MarkDetails',
        ),
    ]
