# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0003_auto_20190603_0913'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentdetails',
            table='student_detail',
        ),
        migrations.AlterModelTable(
            name='subjectdetails',
            table='subject_detail',
        ),
        migrations.AlterModelTable(
            name='teacherdetails',
            table='teacher_detail',
        ),
    ]
