# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0004_auto_20190603_1051'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentdetails',
            table='student_details',
        ),
        migrations.AlterModelTable(
            name='subjectdetails',
            table='subject_details',
        ),
        migrations.AlterModelTable(
            name='teacherdetails',
            table='teacher_details',
        ),
    ]
